# -*- coding: utf-8 -*-
"""Ch2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbA4WJT1ZOMK0j4p8AG_mhMfwf4Ihp_e
"""



"""# This is Heading 1
## This is Heading 2
### This is Heading 3
#### This is Heading 4
##### This is Heading 5
###### This is Heading 6

This is a simple unformatted text.

This contains a **bold word**.

This contains an *italic word*

Unordered, bulleted list:
* item 1
* item 2
* item 3

Ordered list:
1.   List item 1
2.   List item 2

Text formated as Python code:
```python
for a in range(10):
    print(a)
```


> This is an indented block
"""

